name: Docker Image CI
on:
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --file ./Dockerfile \
            --output type=image .
